version: '3.8'
services:
  sinatra:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./public/uploads:/app/public/uploads
    command: rerun --background --pattern **/*.{rb} ruby app.rb
    environment:
      DATABASE_URL: postgres://admin:tad@db:5432/mydatabase

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      POSTGRES_USER: postgres
    depends_on:
      - db

volumes:
  postgres_data:
  unify_documents: