source 'https://rubygems.org'
gem 'pg'
gem 'puma'
gem 'rerun'
gem 'sinatra'
gem 'sinatra-cors'
gem 'sinatra-contrib'
gem 'pdf-reader'
gem 'dotenv'
gem 'ruby-openai'
gem 'base64'
gem 'open-uri'
gem 'rtesseract'
gem 'mini_magick'
gem 'tesseract-ocr'
gem 'google-cloud-vision'
group :test do
  gem 'rspec'
  gem 'rack-test'
end
